// Copyright 2019 (c) Microsoft Corporation.
// Licensed under the MIT license.

// Author:
//
//	Auto Generated on 6/6/2024 using wmigen
//	Source ReplicationCapabilities_SupportedSynchronousActions
//
// ////////////////////////////////////////////
package providers_v2

// ReplicationCapabilities_SupportedSynchronousActions
type ReplicationCapabilities_SupportedSynchronousActions int

const (
	// CreateElementReplica enum
	ReplicationCapabilities_SupportedSynchronousActions_CreateElementReplica ReplicationCapabilities_SupportedSynchronousActions = 2
	// CreateGroupReplica enum
	ReplicationCapabilities_SupportedSynchronousActions_CreateGroupReplica ReplicationCapabilities_SupportedSynchronousActions = 3
	// CreateSynchronizationAspect enum
	ReplicationCapabilities_SupportedSynchronousActions_CreateSynchronizationAspect ReplicationCapabilities_SupportedSynchronousActions = 4
	// ModifyReplicaSynchronization enum
	ReplicationCapabilities_SupportedSynchronousActions_ModifyReplicaSynchronization ReplicationCapabilities_SupportedSynchronousActions = 5
	// ModifyListSynchronization enum
	ReplicationCapabilities_SupportedSynchronousActions_ModifyListSynchronization ReplicationCapabilities_SupportedSynchronousActions = 6
	// ModifySettingsDefineState enum
	ReplicationCapabilities_SupportedSynchronousActions_ModifySettingsDefineState ReplicationCapabilities_SupportedSynchronousActions = 7
	// GetAvailableTargetElements enum
	ReplicationCapabilities_SupportedSynchronousActions_GetAvailableTargetElements ReplicationCapabilities_SupportedSynchronousActions = 8
	// GetPeerSystems enum
	ReplicationCapabilities_SupportedSynchronousActions_GetPeerSystems ReplicationCapabilities_SupportedSynchronousActions = 9
	// GetReplicationRelationships enum
	ReplicationCapabilities_SupportedSynchronousActions_GetReplicationRelationships ReplicationCapabilities_SupportedSynchronousActions = 10
	// GetServiceAccessPoints enum
	ReplicationCapabilities_SupportedSynchronousActions_GetServiceAccessPoints ReplicationCapabilities_SupportedSynchronousActions = 11
	// CreateGroup enum
	ReplicationCapabilities_SupportedSynchronousActions_CreateGroup ReplicationCapabilities_SupportedSynchronousActions = 12
	// DeleteGroup enum
	ReplicationCapabilities_SupportedSynchronousActions_DeleteGroup ReplicationCapabilities_SupportedSynchronousActions = 13
	// AddMembers enum
	ReplicationCapabilities_SupportedSynchronousActions_AddMembers ReplicationCapabilities_SupportedSynchronousActions = 14
	// RemoveMembers enum
	ReplicationCapabilities_SupportedSynchronousActions_RemoveMembers ReplicationCapabilities_SupportedSynchronousActions = 15
	// AddReplicationEntity enum
	ReplicationCapabilities_SupportedSynchronousActions_AddReplicationEntity ReplicationCapabilities_SupportedSynchronousActions = 16
	// AddServiceAccessPoint enum
	ReplicationCapabilities_SupportedSynchronousActions_AddServiceAccessPoint ReplicationCapabilities_SupportedSynchronousActions = 17
	// AddSharedSecret enum
	ReplicationCapabilities_SupportedSynchronousActions_AddSharedSecret ReplicationCapabilities_SupportedSynchronousActions = 18
	// CreateListReplica enum
	ReplicationCapabilities_SupportedSynchronousActions_CreateListReplica ReplicationCapabilities_SupportedSynchronousActions = 19
	// CreateGroupReplicaFromElements enum
	ReplicationCapabilities_SupportedSynchronousActions_CreateGroupReplicaFromElements ReplicationCapabilities_SupportedSynchronousActions = 20
	// GetReplicationRelationshipInstances enum
	ReplicationCapabilities_SupportedSynchronousActions_GetReplicationRelationshipInstances ReplicationCapabilities_SupportedSynchronousActions = 21
	// ModifyListSettingsDefineState enum
	ReplicationCapabilities_SupportedSynchronousActions_ModifyListSettingsDefineState ReplicationCapabilities_SupportedSynchronousActions = 22
	// CreateRemoteReplicationCollection enum
	ReplicationCapabilities_SupportedSynchronousActions_CreateRemoteReplicationCollection ReplicationCapabilities_SupportedSynchronousActions = 23
	// AddToRemoteReplicationCollection enum
	ReplicationCapabilities_SupportedSynchronousActions_AddToRemoteReplicationCollection ReplicationCapabilities_SupportedSynchronousActions = 24
	// RemoveFromRemoteReplicationCollection enum
	ReplicationCapabilities_SupportedSynchronousActions_RemoveFromRemoteReplicationCollection ReplicationCapabilities_SupportedSynchronousActions = 25
	// GetSynchronizationAspects enum
	ReplicationCapabilities_SupportedSynchronousActions_GetSynchronizationAspects ReplicationCapabilities_SupportedSynchronousActions = 26
	// GetSynchronizationAspectInstances enum
	ReplicationCapabilities_SupportedSynchronousActions_GetSynchronizationAspectInstances ReplicationCapabilities_SupportedSynchronousActions = 27
	// CreateGroupReplicaFromElementSynchronizations enum
	ReplicationCapabilities_SupportedSynchronousActions_CreateGroupReplicaFromElementSynchronizations ReplicationCapabilities_SupportedSynchronousActions = 28
	// AddElementsToGroupSynchronized enum
	ReplicationCapabilities_SupportedSynchronousActions_AddElementsToGroupSynchronized ReplicationCapabilities_SupportedSynchronousActions = 29
	// ConfirmTargetData enum
	ReplicationCapabilities_SupportedSynchronousActions_ConfirmTargetData ReplicationCapabilities_SupportedSynchronousActions = 30
	// CreateListSynchronizationAspect enum
	ReplicationCapabilities_SupportedSynchronousActions_CreateListSynchronizationAspect ReplicationCapabilities_SupportedSynchronousActions = 31
	// DMTF_Reserved enum
	ReplicationCapabilities_SupportedSynchronousActions_DMTF_Reserved ReplicationCapabilities_SupportedSynchronousActions = 32
	// Vendor_Specific enum
	ReplicationCapabilities_SupportedSynchronousActions_Vendor_Specific ReplicationCapabilities_SupportedSynchronousActions = 33
)
