// Copyright 2019 (c) Microsoft Corporation.
// Licensed under the MIT license.

//
// Author:
//      Auto Generated on 3/19/2020 using wmigen
//      Source ReplicationCapabilities_SupportedAsynchronousActions
//////////////////////////////////////////////
package providers_v2

// ReplicationCapabilities_SupportedAsynchronousActions
type ReplicationCapabilities_SupportedAsynchronousActions int

const (
	// CreateElementReplica enum
	ReplicationCapabilities_SupportedAsynchronousActions_CreateElementReplica ReplicationCapabilities_SupportedAsynchronousActions = 2
	// CreateGroupReplica enum
	ReplicationCapabilities_SupportedAsynchronousActions_CreateGroupReplica ReplicationCapabilities_SupportedAsynchronousActions = 3
	// CreateSynchronizationAspect enum
	ReplicationCapabilities_SupportedAsynchronousActions_CreateSynchronizationAspect ReplicationCapabilities_SupportedAsynchronousActions = 4
	// ModifyReplicaSynchronization enum
	ReplicationCapabilities_SupportedAsynchronousActions_ModifyReplicaSynchronization ReplicationCapabilities_SupportedAsynchronousActions = 5
	// ModifyListSynchronization enum
	ReplicationCapabilities_SupportedAsynchronousActions_ModifyListSynchronization ReplicationCapabilities_SupportedAsynchronousActions = 6
	// ModifySettingsDefineState enum
	ReplicationCapabilities_SupportedAsynchronousActions_ModifySettingsDefineState ReplicationCapabilities_SupportedAsynchronousActions = 7
	// GetAvailableTargetElements enum
	ReplicationCapabilities_SupportedAsynchronousActions_GetAvailableTargetElements ReplicationCapabilities_SupportedAsynchronousActions = 8
	// GetPeerSystems enum
	ReplicationCapabilities_SupportedAsynchronousActions_GetPeerSystems ReplicationCapabilities_SupportedAsynchronousActions = 9
	// GetReplicationRelationships enum
	ReplicationCapabilities_SupportedAsynchronousActions_GetReplicationRelationships ReplicationCapabilities_SupportedAsynchronousActions = 10
	// GetServiceAccessPoints enum
	ReplicationCapabilities_SupportedAsynchronousActions_GetServiceAccessPoints ReplicationCapabilities_SupportedAsynchronousActions = 11
	// CreateListReplica enum
	ReplicationCapabilities_SupportedAsynchronousActions_CreateListReplica ReplicationCapabilities_SupportedAsynchronousActions = 19
	// CreateGroupReplicaFromElements enum
	ReplicationCapabilities_SupportedAsynchronousActions_CreateGroupReplicaFromElements ReplicationCapabilities_SupportedAsynchronousActions = 20
	// GetReplicationRelationshipInstances enum
	ReplicationCapabilities_SupportedAsynchronousActions_GetReplicationRelationshipInstances ReplicationCapabilities_SupportedAsynchronousActions = 21
	// ModifyListSettingsDefineState enum
	ReplicationCapabilities_SupportedAsynchronousActions_ModifyListSettingsDefineState ReplicationCapabilities_SupportedAsynchronousActions = 22
	// CreateRemoteReplicationCollection enum
	ReplicationCapabilities_SupportedAsynchronousActions_CreateRemoteReplicationCollection ReplicationCapabilities_SupportedAsynchronousActions = 23
	// AddToRemoteReplicationCollection enum
	ReplicationCapabilities_SupportedAsynchronousActions_AddToRemoteReplicationCollection ReplicationCapabilities_SupportedAsynchronousActions = 24
	// RemoveFromRemoteReplicationCollection enum
	ReplicationCapabilities_SupportedAsynchronousActions_RemoveFromRemoteReplicationCollection ReplicationCapabilities_SupportedAsynchronousActions = 25
	// GetSynchronizationAspects enum
	ReplicationCapabilities_SupportedAsynchronousActions_GetSynchronizationAspects ReplicationCapabilities_SupportedAsynchronousActions = 26
	// GetSynchronizationAspectInstances enum
	ReplicationCapabilities_SupportedAsynchronousActions_GetSynchronizationAspectInstances ReplicationCapabilities_SupportedAsynchronousActions = 27
	// CreateGroupReplicaFromElementSynchronizations enum
	ReplicationCapabilities_SupportedAsynchronousActions_CreateGroupReplicaFromElementSynchronizations ReplicationCapabilities_SupportedAsynchronousActions = 28
	// AddElementsToGroupSynchronized enum
	ReplicationCapabilities_SupportedAsynchronousActions_AddElementsToGroupSynchronized ReplicationCapabilities_SupportedAsynchronousActions = 29
	// ConfirmTargetData enum
	ReplicationCapabilities_SupportedAsynchronousActions_ConfirmTargetData ReplicationCapabilities_SupportedAsynchronousActions = 30
	// CreateListSynchronizationAspect enum
	ReplicationCapabilities_SupportedAsynchronousActions_CreateListSynchronizationAspect ReplicationCapabilities_SupportedAsynchronousActions = 31
	// DMTF_Reserved enum
	ReplicationCapabilities_SupportedAsynchronousActions_DMTF_Reserved ReplicationCapabilities_SupportedAsynchronousActions = 32
	// Vendor_Specific enum
	ReplicationCapabilities_SupportedAsynchronousActions_Vendor_Specific ReplicationCapabilities_SupportedAsynchronousActions = 33
)
