// Copyright 2019 (c) Microsoft Corporation.
// Licensed under the MIT license.

//
// Author:
//      Auto Generated on 6/12/2024 using wmigen
//      Source root.virtualization.v2
//////////////////////////////////////////////
package v2

import (
	"github.com/microsoft/wmi/pkg/base/query"
	cim "github.com/microsoft/wmi/pkg/wmiinstance"
)

// Msvm_CollectionManagementService struct
type Msvm_CollectionManagementService struct {
	*CIM_Service
}

func NewMsvm_CollectionManagementServiceEx1(instance *cim.WmiInstance) (newInstance *Msvm_CollectionManagementService, err error) {
	tmp, err := NewCIM_ServiceEx1(instance)

	if err != nil {
		return
	}
	newInstance = &Msvm_CollectionManagementService{
		CIM_Service: tmp,
	}
	return
}

func NewMsvm_CollectionManagementServiceEx6(hostName string,
	wmiNamespace string,
	userName string,
	password string,
	domainName string,
	query *query.WmiQuery) (newInstance *Msvm_CollectionManagementService, err error) {
	tmp, err := NewCIM_ServiceEx6(hostName, wmiNamespace, userName, password, domainName, query)

	if err != nil {
		return
	}
	newInstance = &Msvm_CollectionManagementService{
		CIM_Service: tmp,
	}
	return
}

//

// <param name="Id" type="string ">String containing a GUID used to identify the group. The GUID must be unique, or the call will fail. If no string is specified, a new unique Id will be generated by the service.</param>
// <param name="Name" type="string ">String containing a user defined name for the new collection. If no string is specified, the default new collection name will be used.</param>
// <param name="Type" type="uint16 ">An enumeration value that specifies what type of collection object to create.</param>

// <param name="DefinedCollection" type="CIM_CollectionOfMSEs ">If successful, outputs a string containing a reference to the created collection.</param>
// <param name="Job" type="CIM_ConcreteJob "></param>
// <param name="ReturnValue" type="uint32 "></param>
func (instance *Msvm_CollectionManagementService) DefineCollection( /* IN */ Name string,
	/* IN */ Id string,
	/* IN */ Type uint16,
	/* OUT */ DefinedCollection CIM_CollectionOfMSEs,
	/* OUT */ Job CIM_ConcreteJob,
	/*Custom IN*/ Action cim.UserAction,
	/*Custon IN*/ PercentComplete uint32,
	/*Custon IN*/ Timeout uint32) (result uint32, err error) {
	retVal, err := instance.InvokeMethodAsync("DefineCollection", Action, PercentComplete, Timeout, Name, Id, Type)
	if err != nil {
		return
	}
	retValue := retVal[0].(int32)
	result = uint32(retValue)
	return

}

//

// <param name="Collection" type="CIM_CollectionOfMSEs ">A reference to the collection that will be deleted.</param>

// <param name="Job" type="CIM_ConcreteJob "></param>
// <param name="ReturnValue" type="uint32 "></param>
func (instance *Msvm_CollectionManagementService) DestroyCollection( /* IN */ Collection CIM_CollectionOfMSEs,
	/* OUT */ Job CIM_ConcreteJob,
	/*Custom IN*/ Action cim.UserAction,
	/*Custon IN*/ PercentComplete uint32,
	/*Custon IN*/ Timeout uint32) (result uint32, err error) {
	retVal, err := instance.InvokeMethodAsync("DestroyCollection", Action, PercentComplete, Timeout, Collection)
	if err != nil {
		return
	}
	retValue := retVal[0].(int32)
	result = uint32(retValue)
	return

}

//

// <param name="Collection" type="CIM_CollectionOfMSEs ">A reference to the collection that will be renamed.</param>
// <param name="NewName" type="string ">A string containing the new name for the collection.</param>

// <param name="Job" type="CIM_ConcreteJob "></param>
// <param name="ReturnValue" type="uint32 "></param>
func (instance *Msvm_CollectionManagementService) RenameCollection( /* IN */ Collection CIM_CollectionOfMSEs,
	/* IN */ NewName string,
	/* OUT */ Job CIM_ConcreteJob,
	/*Custom IN*/ Action cim.UserAction,
	/*Custon IN*/ PercentComplete uint32,
	/*Custon IN*/ Timeout uint32) (result uint32, err error) {
	retVal, err := instance.InvokeMethodAsync("RenameCollection", Action, PercentComplete, Timeout, Collection, NewName)
	if err != nil {
		return
	}
	retValue := retVal[0].(int32)
	result = uint32(retValue)
	return

}

//

// <param name="Collection" type="CIM_CollectionOfMSEs ">A reference to the collection the member should be added to.</param>
// <param name="Member" type="CIM_ManagedElement ">A reference to the the member that should be added to the collection. This should refer to either an Msvm_ComputerSystem, an Msvm_VirtualSystemCollection, or an Msvm_ManagementCollection.</param>

// <param name="Job" type="CIM_ConcreteJob "></param>
// <param name="ReturnValue" type="uint32 "></param>
func (instance *Msvm_CollectionManagementService) AddMember( /* IN */ Member CIM_ManagedElement,
	/* IN */ Collection CIM_CollectionOfMSEs,
	/* OUT */ Job CIM_ConcreteJob,
	/*Custom IN*/ Action cim.UserAction,
	/*Custon IN*/ PercentComplete uint32,
	/*Custon IN*/ Timeout uint32) (result uint32, err error) {
	retVal, err := instance.InvokeMethodAsync("AddMember", Action, PercentComplete, Timeout, Member, Collection)
	if err != nil {
		return
	}
	retValue := retVal[0].(int32)
	result = uint32(retValue)
	return

}

//

// <param name="Collection" type="CIM_CollectionOfMSEs ">A reference to the collection the member should be removed from.</param>
// <param name="Member" type="CIM_ManagedElement ">A reference to the the member that should be removed from the collection. This should refer to either an Msvm_ComputerSystem, an Msvm_VirtualSystemCollection, or an Msvm_ManagementCollection.</param>

// <param name="Job" type="CIM_ConcreteJob "></param>
// <param name="ReturnValue" type="uint32 "></param>
func (instance *Msvm_CollectionManagementService) RemoveMember( /* IN */ Member CIM_ManagedElement,
	/* IN */ Collection CIM_CollectionOfMSEs,
	/* OUT */ Job CIM_ConcreteJob,
	/*Custom IN*/ Action cim.UserAction,
	/*Custon IN*/ PercentComplete uint32,
	/*Custon IN*/ Timeout uint32) (result uint32, err error) {
	retVal, err := instance.InvokeMethodAsync("RemoveMember", Action, PercentComplete, Timeout, Member, Collection)
	if err != nil {
		return
	}
	retValue := retVal[0].(int32)
	result = uint32(retValue)
	return

}

//

// <param name="CollectionId" type="string ">A string containing the GUID instance ID for the collection from which the member should be removed.</param>
// <param name="Member" type="CIM_ManagedElement ">A reference to the the member that should be removed from the collection. This should refer to either an Msvm_ComputerSystem, an Msvm_VirtualSystemCollection, or an Msvm_ManagementCollection.</param>

// <param name="Job" type="CIM_ConcreteJob "></param>
// <param name="ReturnValue" type="uint32 "></param>
func (instance *Msvm_CollectionManagementService) RemoveMemberById( /* IN */ Member CIM_ManagedElement,
	/* IN */ CollectionId string,
	/* OUT */ Job CIM_ConcreteJob,
	/*Custom IN*/ Action cim.UserAction,
	/*Custon IN*/ PercentComplete uint32,
	/*Custon IN*/ Timeout uint32) (result uint32, err error) {
	retVal, err := instance.InvokeMethodAsync("RemoveMemberById", Action, PercentComplete, Timeout, Member, CollectionId)
	if err != nil {
		return
	}
	retValue := retVal[0].(int32)
	result = uint32(retValue)
	return

}

func (instance *Msvm_CollectionManagementService) GetRelatedComputerSystem() (value *cim.WmiInstance, err error) {
	return instance.GetRelated("Msvm_ComputerSystem")
}
