// Copyright 2019 (c) Microsoft Corporation.
// Licensed under the MIT license.

//
// Author:
//      Auto Generated on 6/14/2024 using wmigen
//      Source VirtualSystemManagementCapabilities_SynchronousMethodsSupported
//////////////////////////////////////////////
package v2

// VirtualSystemManagementCapabilities_SynchronousMethodsSupported
type VirtualSystemManagementCapabilities_SynchronousMethodsSupported int

const (
	// DefineSystemSupported enum
	VirtualSystemManagementCapabilities_SynchronousMethodsSupported_DefineSystemSupported VirtualSystemManagementCapabilities_SynchronousMethodsSupported = 2
	// DestroySystemSupported enum
	VirtualSystemManagementCapabilities_SynchronousMethodsSupported_DestroySystemSupported VirtualSystemManagementCapabilities_SynchronousMethodsSupported = 3
	// DestroySystemConfigurationSupported enum
	VirtualSystemManagementCapabilities_SynchronousMethodsSupported_DestroySystemConfigurationSupported VirtualSystemManagementCapabilities_SynchronousMethodsSupported = 4
	// ModifyResourceSettingsSupported enum
	VirtualSystemManagementCapabilities_SynchronousMethodsSupported_ModifyResourceSettingsSupported VirtualSystemManagementCapabilities_SynchronousMethodsSupported = 5
	// ModifySystemSettingsSupported enum
	VirtualSystemManagementCapabilities_SynchronousMethodsSupported_ModifySystemSettingsSupported VirtualSystemManagementCapabilities_SynchronousMethodsSupported = 6
	// RemoveResourcesSupported enum
	VirtualSystemManagementCapabilities_SynchronousMethodsSupported_RemoveResourcesSupported VirtualSystemManagementCapabilities_SynchronousMethodsSupported = 7
	// SelectSystemConfigurationSupported enum
	VirtualSystemManagementCapabilities_SynchronousMethodsSupported_SelectSystemConfigurationSupported VirtualSystemManagementCapabilities_SynchronousMethodsSupported = 8
	// SnapshotSystemSupported enum
	VirtualSystemManagementCapabilities_SynchronousMethodsSupported_SnapshotSystemSupported VirtualSystemManagementCapabilities_SynchronousMethodsSupported = 9
	// AddResourcesSupported enum
	VirtualSystemManagementCapabilities_SynchronousMethodsSupported_AddResourcesSupported VirtualSystemManagementCapabilities_SynchronousMethodsSupported = 10
	// DMTF_Reserved enum
	VirtualSystemManagementCapabilities_SynchronousMethodsSupported_DMTF_Reserved VirtualSystemManagementCapabilities_SynchronousMethodsSupported = 11
	// Vendor_Reserved enum
	VirtualSystemManagementCapabilities_SynchronousMethodsSupported_Vendor_Reserved VirtualSystemManagementCapabilities_SynchronousMethodsSupported = 12
)
