// Copyright 2019 (c) Microsoft Corporation.
// Licensed under the MIT license.

//
// Author:
//      Auto Generated on 3/19/2020 using wmigen
//      Source VirtualSystemManagementCapabilities_AsynchronousMethodsSupported
//////////////////////////////////////////////
package v2

// VirtualSystemManagementCapabilities_AsynchronousMethodsSupported
type VirtualSystemManagementCapabilities_AsynchronousMethodsSupported int

const (
	// DefineSystemSupported enum
	VirtualSystemManagementCapabilities_AsynchronousMethodsSupported_DefineSystemSupported VirtualSystemManagementCapabilities_AsynchronousMethodsSupported = 2
	// DestroySystemSupported enum
	VirtualSystemManagementCapabilities_AsynchronousMethodsSupported_DestroySystemSupported VirtualSystemManagementCapabilities_AsynchronousMethodsSupported = 3
	// DestroySystemConfigurationSupported enum
	VirtualSystemManagementCapabilities_AsynchronousMethodsSupported_DestroySystemConfigurationSupported VirtualSystemManagementCapabilities_AsynchronousMethodsSupported = 4
	// ModifyResourceSettingsSupported enum
	VirtualSystemManagementCapabilities_AsynchronousMethodsSupported_ModifyResourceSettingsSupported VirtualSystemManagementCapabilities_AsynchronousMethodsSupported = 5
	// ModifySystemSettingsSupported enum
	VirtualSystemManagementCapabilities_AsynchronousMethodsSupported_ModifySystemSettingsSupported VirtualSystemManagementCapabilities_AsynchronousMethodsSupported = 6
	// RemoveResourcesSupported enum
	VirtualSystemManagementCapabilities_AsynchronousMethodsSupported_RemoveResourcesSupported VirtualSystemManagementCapabilities_AsynchronousMethodsSupported = 7
	// SelectSystemConfigurationSupported enum
	VirtualSystemManagementCapabilities_AsynchronousMethodsSupported_SelectSystemConfigurationSupported VirtualSystemManagementCapabilities_AsynchronousMethodsSupported = 8
	// SnapshotSystemSupported enum
	VirtualSystemManagementCapabilities_AsynchronousMethodsSupported_SnapshotSystemSupported VirtualSystemManagementCapabilities_AsynchronousMethodsSupported = 9
	// AddResourcesSupported enum
	VirtualSystemManagementCapabilities_AsynchronousMethodsSupported_AddResourcesSupported VirtualSystemManagementCapabilities_AsynchronousMethodsSupported = 10
	// DMTF_Reserved enum
	VirtualSystemManagementCapabilities_AsynchronousMethodsSupported_DMTF_Reserved VirtualSystemManagementCapabilities_AsynchronousMethodsSupported = 11
	// Vendor_Reserved enum
	VirtualSystemManagementCapabilities_AsynchronousMethodsSupported_Vendor_Reserved VirtualSystemManagementCapabilities_AsynchronousMethodsSupported = 12
)
