// Copyright 2019 (c) Microsoft Corporation.
// Licensed under the MIT license.

//
// Author:
//      Auto Generated on 6/6/2024 using wmigen
//      Source NETIO_Flags
//////////////////////////////////////////////
package wmi

// NETIO_Flags 
type NETIO_Flags int
const(
	// NETIO_TRACE_SEND enum
	NETIO_Flags_NETIO_TRACE_SEND NETIO_Flags = 1
	// NETIO_TRACE_RECEIVE enum
	NETIO_Flags_NETIO_TRACE_RECEIVE NETIO_Flags = 2
	// NETIO_TRACE_INTERFACE enum
	NETIO_Flags_NETIO_TRACE_INTERFACE NETIO_Flags = 3
	// NETIO_TRACE_NMR enum
	NETIO_Flags_NETIO_TRACE_NMR NETIO_Flags = 4
	// NETIO_TRACE_NSI enum
	NETIO_Flags_NETIO_TRACE_NSI NETIO_Flags = 5
	// NETIO_TRACE_FRAMING enum
	NETIO_Flags_NETIO_TRACE_FRAMING NETIO_Flags = 6
	// NETIO_TRACE_NETWORK enum
	NETIO_Flags_NETIO_TRACE_NETWORK NETIO_Flags = 7
	// NETIO_TRACE_TRANSPORT enum
	NETIO_Flags_NETIO_TRACE_TRANSPORT NETIO_Flags = 8
	// NETIO_TRACE_TUNNEL enum
	NETIO_Flags_NETIO_TRACE_TUNNEL NETIO_Flags = 9
	// NETIO_TRACE_TDX enum
	NETIO_Flags_NETIO_TRACE_TDX NETIO_Flags = 10
	// NETIO_TRACE_LEGACY enum
	NETIO_Flags_NETIO_TRACE_LEGACY NETIO_Flags = 11
	// NETIO_TRACE_PACER enum
	NETIO_Flags_NETIO_TRACE_PACER NETIO_Flags = 12
	// WFP_TRACE_BASE enum
	NETIO_Flags_WFP_TRACE_BASE NETIO_Flags = 13
	// WFP_TRACE_FE enum
	NETIO_Flags_WFP_TRACE_FE NETIO_Flags = 14
	// WFP_TRACE_STM enum
	NETIO_Flags_WFP_TRACE_STM NETIO_Flags = 15
	// WFP_TRACE_IPSEC enum
	NETIO_Flags_WFP_TRACE_IPSEC NETIO_Flags = 16
	// WFP_TRACE_ALE enum
	NETIO_Flags_WFP_TRACE_ALE NETIO_Flags = 17
	// WFP_TRACE_OFFLOAD enum
	NETIO_Flags_WFP_TRACE_OFFLOAD NETIO_Flags = 18
	// NETIO_TRACE_EQOS enum
	NETIO_Flags_NETIO_TRACE_EQOS NETIO_Flags = 19
	// NETIO_TRACE_RSS enum
	NETIO_Flags_NETIO_TRACE_RSS NETIO_Flags = 20
	// NETIO_TRACE_NRT enum
	NETIO_Flags_NETIO_TRACE_NRT NETIO_Flags = 21
	// NETIO_TRACE_NCM enum
	NETIO_Flags_NETIO_TRACE_NCM NETIO_Flags = 22
	// NETIO_TRACE_IPHLPAPI enum
	NETIO_Flags_NETIO_TRACE_IPHLPAPI NETIO_Flags = 23
	// NETIO_TRACE_IPSNPI enum
	NETIO_Flags_NETIO_TRACE_IPSNPI NETIO_Flags = 24
)

