// Copyright 2019 (c) Microsoft Corporation.
// Licensed under the MIT license.

// Author:
//
//	Auto Generated on 6/6/2024 using wmigen
//	Source SMBIOSError_Type
//
// ////////////////////////////////////////////
package wmi

// SMBIOSError_Type
type SMBIOSError_Type int

const (
	// MCA_WARNING_CACHE enum
	SMBIOSError_Type_MCA_WARNING_CACHE SMBIOSError_Type = 1
	// MCA_ERROR_CACHE enum
	SMBIOSError_Type_MCA_ERROR_CACHE SMBIOSError_Type = 2
	// MCA_WARNING_TLB enum
	SMBIOSError_Type_MCA_WARNING_TLB SMBIOSError_Type = 3
	// MCA_ERROR_TLB enum
	SMBIOSError_Type_MCA_ERROR_TLB SMBIOSError_Type = 4
	// MCA_WARNING_CPU_BUS enum
	SMBIOSError_Type_MCA_WARNING_CPU_BUS SMBIOSError_Type = 5
	// MCA_ERROR_CPU_BUS enum
	SMBIOSError_Type_MCA_ERROR_CPU_BUS SMBIOSError_Type = 6
	// MCA_WARNING_REGISTER_FILE enum
	SMBIOSError_Type_MCA_WARNING_REGISTER_FILE SMBIOSError_Type = 7
	// MCA_ERROR_REGISTER_FILE enum
	SMBIOSError_Type_MCA_ERROR_REGISTER_FILE SMBIOSError_Type = 8
	// MCA_WARNING_MAS enum
	SMBIOSError_Type_MCA_WARNING_MAS SMBIOSError_Type = 9
	// MCA_ERROR_MAS enum
	SMBIOSError_Type_MCA_ERROR_MAS SMBIOSError_Type = 10
	// MCA_WARNING_MEM_UNKNOWN enum
	SMBIOSError_Type_MCA_WARNING_MEM_UNKNOWN SMBIOSError_Type = 11
	// MCA_ERROR_MEM_UNKNOWN enum
	SMBIOSError_Type_MCA_ERROR_MEM_UNKNOWN SMBIOSError_Type = 12
	// MCA_WARNING_MEM_1_2 enum
	SMBIOSError_Type_MCA_WARNING_MEM_1_2 SMBIOSError_Type = 13
	// MCA_ERROR_MEM_1_2 enum
	SMBIOSError_Type_MCA_ERROR_MEM_1_2 SMBIOSError_Type = 14
	// MCA_WARNING_MEM_1_2_5 enum
	SMBIOSError_Type_MCA_WARNING_MEM_1_2_5 SMBIOSError_Type = 15
	// MCA_ERROR_MEM_1_2_5 enum
	SMBIOSError_Type_MCA_ERROR_MEM_1_2_5 SMBIOSError_Type = 16
	// MCA_WARNING_MEM_1_2_5_4 enum
	SMBIOSError_Type_MCA_WARNING_MEM_1_2_5_4 SMBIOSError_Type = 17
	// MCA_ERROR_MEM_1_2_5_4 enum
	SMBIOSError_Type_MCA_ERROR_MEM_1_2_5_4 SMBIOSError_Type = 18
	// MCA_WARNING_SYSTEM_EVENT enum
	SMBIOSError_Type_MCA_WARNING_SYSTEM_EVENT SMBIOSError_Type = 19
	// MCA_ERROR_SYSTEM_EVENT enum
	SMBIOSError_Type_MCA_ERROR_SYSTEM_EVENT SMBIOSError_Type = 20
	// MCA_WARNING_PCI_BUS_PARITY enum
	SMBIOSError_Type_MCA_WARNING_PCI_BUS_PARITY SMBIOSError_Type = 21
	// MCA_ERROR_PCI_BUS_PARITY enum
	SMBIOSError_Type_MCA_ERROR_PCI_BUS_PARITY SMBIOSError_Type = 22
	// MCA_WARNING_PCI_BUS_PARITY_NO_INFO enum
	SMBIOSError_Type_MCA_WARNING_PCI_BUS_PARITY_NO_INFO SMBIOSError_Type = 23
	// MCA_ERROR_PCI_BUS_PARITY_NO_INFO enum
	SMBIOSError_Type_MCA_ERROR_PCI_BUS_PARITY_NO_INFO SMBIOSError_Type = 24
	// MCA_WARNING_PCI_BUS_SERR enum
	SMBIOSError_Type_MCA_WARNING_PCI_BUS_SERR SMBIOSError_Type = 25
	// MCA_ERROR_PCI_BUS_SERR enum
	SMBIOSError_Type_MCA_ERROR_PCI_BUS_SERR SMBIOSError_Type = 26
	// MCA_WARNING_PCI_BUS_SERR_NO_INFO enum
	SMBIOSError_Type_MCA_WARNING_PCI_BUS_SERR_NO_INFO SMBIOSError_Type = 27
	// MCA_ERROR_PCI_BUS_SERR_NO_INFO enum
	SMBIOSError_Type_MCA_ERROR_PCI_BUS_SERR_NO_INFO SMBIOSError_Type = 28
	// MCA_WARNING_PCI_BUS_MASTER_ABORT enum
	SMBIOSError_Type_MCA_WARNING_PCI_BUS_MASTER_ABORT SMBIOSError_Type = 29
	// MCA_ERROR_PCI_BUS_MASTER_ABORT enum
	SMBIOSError_Type_MCA_ERROR_PCI_BUS_MASTER_ABORT SMBIOSError_Type = 30
	// MCA_WARNING_PCI_BUS_MASTER_ABORT_NO_INFO enum
	SMBIOSError_Type_MCA_WARNING_PCI_BUS_MASTER_ABORT_NO_INFO SMBIOSError_Type = 31
	// MCA_ERROR_PCI_BUS_MASTER_ABORT_NO_INFO enum
	SMBIOSError_Type_MCA_ERROR_PCI_BUS_MASTER_ABORT_NO_INFO SMBIOSError_Type = 32
	// MCA_WARNING_PCI_BUS_TIMEOUT enum
	SMBIOSError_Type_MCA_WARNING_PCI_BUS_TIMEOUT SMBIOSError_Type = 33
	// MCA_ERROR_PCI_BUS_TIMEOUT enum
	SMBIOSError_Type_MCA_ERROR_PCI_BUS_TIMEOUT SMBIOSError_Type = 34
	// MCA_WARNING_PCI_BUS_TIMEOUT_NO_INFO enum
	SMBIOSError_Type_MCA_WARNING_PCI_BUS_TIMEOUT_NO_INFO SMBIOSError_Type = 35
	// MCA_ERROR_PCI_BUS_TIMEOUT_NO_INFO enum
	SMBIOSError_Type_MCA_ERROR_PCI_BUS_TIMEOUT_NO_INFO SMBIOSError_Type = 36
	// MCA_WARNING_PCI_BUS_UNKNOWN enum
	SMBIOSError_Type_MCA_WARNING_PCI_BUS_UNKNOWN SMBIOSError_Type = 37
	// MCA_ERROR_PCI_BUS_UNKNOWN enum
	SMBIOSError_Type_MCA_ERROR_PCI_BUS_UNKNOWN SMBIOSError_Type = 38
	// MCA_WARNING_PCI_DEVICE enum
	SMBIOSError_Type_MCA_WARNING_PCI_DEVICE SMBIOSError_Type = 39
	// MCA_ERROR_PCI_DEVICE enum
	SMBIOSError_Type_MCA_ERROR_PCI_DEVICE SMBIOSError_Type = 40
	// MCA_WARNING_SMBIOS enum
	SMBIOSError_Type_MCA_WARNING_SMBIOS SMBIOSError_Type = 41
	// MCA_ERROR_SMBIOS enum
	SMBIOSError_Type_MCA_ERROR_SMBIOS SMBIOSError_Type = 42
	// MCA_WARNING_PLATFORM_SPECIFIC enum
	SMBIOSError_Type_MCA_WARNING_PLATFORM_SPECIFIC SMBIOSError_Type = 43
	// MCA_ERROR_PLATFORM_SPECIFIC enum
	SMBIOSError_Type_MCA_ERROR_PLATFORM_SPECIFIC SMBIOSError_Type = 44
	// MCA_WARNING_UNKNOWN enum
	SMBIOSError_Type_MCA_WARNING_UNKNOWN SMBIOSError_Type = 45
	// MCA_ERROR_UNKNOWN enum
	SMBIOSError_Type_MCA_ERROR_UNKNOWN SMBIOSError_Type = 46
	// MCA_WARNING_UNKNOWN_NO_CPU enum
	SMBIOSError_Type_MCA_WARNING_UNKNOWN_NO_CPU SMBIOSError_Type = 47
	// MCA_ERROR_UNKNOWN_NO_CPU enum
	SMBIOSError_Type_MCA_ERROR_UNKNOWN_NO_CPU SMBIOSError_Type = 48
	// MCA_WARNING_CMC_THRESHOLD_EXCEEDED enum
	SMBIOSError_Type_MCA_WARNING_CMC_THRESHOLD_EXCEEDED SMBIOSError_Type = 49
	// MCA_WARNING_CPE_THRESHOLD_EXCEEDED enum
	SMBIOSError_Type_MCA_WARNING_CPE_THRESHOLD_EXCEEDED SMBIOSError_Type = 50
	// MCA_WARNING_CPU_THERMAL_THROTTLED enum
	SMBIOSError_Type_MCA_WARNING_CPU_THERMAL_THROTTLED SMBIOSError_Type = 51
	// MCA_INFO_CPU_THERMAL_THROTTLING_REMOVED enum
	SMBIOSError_Type_MCA_INFO_CPU_THERMAL_THROTTLING_REMOVED SMBIOSError_Type = 52
	// MCA_WARNING_CPU enum
	SMBIOSError_Type_MCA_WARNING_CPU SMBIOSError_Type = 53
	// MCA_ERROR_CPU enum
	SMBIOSError_Type_MCA_ERROR_CPU SMBIOSError_Type = 54
	// MCA_MEMORYHIERARCHY_ERROR enum
	SMBIOSError_Type_MCA_MEMORYHIERARCHY_ERROR SMBIOSError_Type = 55
	// MCA_TLB_ERROR enum
	SMBIOSError_Type_MCA_TLB_ERROR SMBIOSError_Type = 56
	// MCA_BUS_ERROR enum
	SMBIOSError_Type_MCA_BUS_ERROR SMBIOSError_Type = 57
	// MCA_BUS_TIMEOUT_ERROR enum
	SMBIOSError_Type_MCA_BUS_TIMEOUT_ERROR SMBIOSError_Type = 58
	// MCA_INTERNALTIMER_ERROR enum
	SMBIOSError_Type_MCA_INTERNALTIMER_ERROR SMBIOSError_Type = 59
	// MCA_MICROCODE_ROM_PARITY_ERROR enum
	SMBIOSError_Type_MCA_MICROCODE_ROM_PARITY_ERROR SMBIOSError_Type = 60
	// MCA_EXTERNAL_ERROR enum
	SMBIOSError_Type_MCA_EXTERNAL_ERROR SMBIOSError_Type = 61
	// MCA_FRC_ERROR enum
	SMBIOSError_Type_MCA_FRC_ERROR SMBIOSError_Type = 62
)
