// Copyright 2019 (c) Microsoft Corporation.
// Licensed under the MIT license.

// Author:
//
//	Auto Generated on 6/6/2024 using wmigen
//	Source ReplicationCapabilities_SupportedReplicationTypes
//
// ////////////////////////////////////////////
package providers_v2

// ReplicationCapabilities_SupportedReplicationTypes
type ReplicationCapabilities_SupportedReplicationTypes int

const (
	// Synchronous_Mirror_Local enum
	ReplicationCapabilities_SupportedReplicationTypes_Synchronous_Mirror_Local ReplicationCapabilities_SupportedReplicationTypes = 2
	// Asynchronous_Mirror_Local enum
	ReplicationCapabilities_SupportedReplicationTypes_Asynchronous_Mirror_Local ReplicationCapabilities_SupportedReplicationTypes = 3
	// Synchronous_Mirror_Remote enum
	ReplicationCapabilities_SupportedReplicationTypes_Synchronous_Mirror_Remote ReplicationCapabilities_SupportedReplicationTypes = 4
	// Asynchronous_Mirror_Remote enum
	ReplicationCapabilities_SupportedReplicationTypes_Asynchronous_Mirror_Remote ReplicationCapabilities_SupportedReplicationTypes = 5
	// Synchronous_Snapshot_Local enum
	ReplicationCapabilities_SupportedReplicationTypes_Synchronous_Snapshot_Local ReplicationCapabilities_SupportedReplicationTypes = 6
	// Asynchronous_Snapshot_Local enum
	ReplicationCapabilities_SupportedReplicationTypes_Asynchronous_Snapshot_Local ReplicationCapabilities_SupportedReplicationTypes = 7
	// Synchronous_Snapshot_Remote enum
	ReplicationCapabilities_SupportedReplicationTypes_Synchronous_Snapshot_Remote ReplicationCapabilities_SupportedReplicationTypes = 8
	// Asynchronous_Snapshot_Remote enum
	ReplicationCapabilities_SupportedReplicationTypes_Asynchronous_Snapshot_Remote ReplicationCapabilities_SupportedReplicationTypes = 9
	// Synchronous_Clone_Local enum
	ReplicationCapabilities_SupportedReplicationTypes_Synchronous_Clone_Local ReplicationCapabilities_SupportedReplicationTypes = 10
	// Asynchronous_Clone_Local enum
	ReplicationCapabilities_SupportedReplicationTypes_Asynchronous_Clone_Local ReplicationCapabilities_SupportedReplicationTypes = 11
	// Synchronous_Clone_Remote enum
	ReplicationCapabilities_SupportedReplicationTypes_Synchronous_Clone_Remote ReplicationCapabilities_SupportedReplicationTypes = 12
	// Asynchronous_Clone_Remote enum
	ReplicationCapabilities_SupportedReplicationTypes_Asynchronous_Clone_Remote ReplicationCapabilities_SupportedReplicationTypes = 13
	// Synchronous_TokenizedClone_Local enum
	ReplicationCapabilities_SupportedReplicationTypes_Synchronous_TokenizedClone_Local ReplicationCapabilities_SupportedReplicationTypes = 14
	// Asynchronous_TokenizedClone_Local enum
	ReplicationCapabilities_SupportedReplicationTypes_Asynchronous_TokenizedClone_Local ReplicationCapabilities_SupportedReplicationTypes = 15
	// Synchronous_TokenizedClone_Remote enum
	ReplicationCapabilities_SupportedReplicationTypes_Synchronous_TokenizedClone_Remote ReplicationCapabilities_SupportedReplicationTypes = 16
	// Asynchronous_TokenizedClone_Remote enum
	ReplicationCapabilities_SupportedReplicationTypes_Asynchronous_TokenizedClone_Remote ReplicationCapabilities_SupportedReplicationTypes = 17
	// Adaptive_Mirror_Local enum
	ReplicationCapabilities_SupportedReplicationTypes_Adaptive_Mirror_Local ReplicationCapabilities_SupportedReplicationTypes = 18
	// Adaptive_Mirror_Remote enum
	ReplicationCapabilities_SupportedReplicationTypes_Adaptive_Mirror_Remote ReplicationCapabilities_SupportedReplicationTypes = 19
	// Adaptive_Snapshot_Local enum
	ReplicationCapabilities_SupportedReplicationTypes_Adaptive_Snapshot_Local ReplicationCapabilities_SupportedReplicationTypes = 20
	// Adaptive_Snapshot_Remote enum
	ReplicationCapabilities_SupportedReplicationTypes_Adaptive_Snapshot_Remote ReplicationCapabilities_SupportedReplicationTypes = 21
	// Adaptive_Clone_Local enum
	ReplicationCapabilities_SupportedReplicationTypes_Adaptive_Clone_Local ReplicationCapabilities_SupportedReplicationTypes = 22
	// Adaptive_Clone_Remote enum
	ReplicationCapabilities_SupportedReplicationTypes_Adaptive_Clone_Remote ReplicationCapabilities_SupportedReplicationTypes = 23
	// Adaptive_TokenizedClone_Local enum
	ReplicationCapabilities_SupportedReplicationTypes_Adaptive_TokenizedClone_Local ReplicationCapabilities_SupportedReplicationTypes = 24
	// Adaptive_TokenizedClone_Remote enum
	ReplicationCapabilities_SupportedReplicationTypes_Adaptive_TokenizedClone_Remote ReplicationCapabilities_SupportedReplicationTypes = 25
	// DMTF_Reserved enum
	ReplicationCapabilities_SupportedReplicationTypes_DMTF_Reserved ReplicationCapabilities_SupportedReplicationTypes = 26
	// Vendor_Specific enum
	ReplicationCapabilities_SupportedReplicationTypes_Vendor_Specific ReplicationCapabilities_SupportedReplicationTypes = 27
)
