// Copyright 2019 (c) Microsoft Corporation.
// Licensed under the MIT license.

// Author:
//
//	Auto Generated on 6/6/2024 using wmigen
//	Source CPUError_Type
//
// ////////////////////////////////////////////
package wmi

// CPUError_Type
type CPUError_Type int

const (
	// MCA_WARNING_CACHE enum
	CPUError_Type_MCA_WARNING_CACHE CPUError_Type = 1
	// MCA_ERROR_CACHE enum
	CPUError_Type_MCA_ERROR_CACHE CPUError_Type = 2
	// MCA_WARNING_TLB enum
	CPUError_Type_MCA_WARNING_TLB CPUError_Type = 3
	// MCA_ERROR_TLB enum
	CPUError_Type_MCA_ERROR_TLB CPUError_Type = 4
	// MCA_WARNING_CPU_BUS enum
	CPUError_Type_MCA_WARNING_CPU_BUS CPUError_Type = 5
	// MCA_ERROR_CPU_BUS enum
	CPUError_Type_MCA_ERROR_CPU_BUS CPUError_Type = 6
	// MCA_WARNING_REGISTER_FILE enum
	CPUError_Type_MCA_WARNING_REGISTER_FILE CPUError_Type = 7
	// MCA_ERROR_REGISTER_FILE enum
	CPUError_Type_MCA_ERROR_REGISTER_FILE CPUError_Type = 8
	// MCA_WARNING_MAS enum
	CPUError_Type_MCA_WARNING_MAS CPUError_Type = 9
	// MCA_ERROR_MAS enum
	CPUError_Type_MCA_ERROR_MAS CPUError_Type = 10
	// MCA_WARNING_MEM_UNKNOWN enum
	CPUError_Type_MCA_WARNING_MEM_UNKNOWN CPUError_Type = 11
	// MCA_ERROR_MEM_UNKNOWN enum
	CPUError_Type_MCA_ERROR_MEM_UNKNOWN CPUError_Type = 12
	// MCA_WARNING_MEM_1_2 enum
	CPUError_Type_MCA_WARNING_MEM_1_2 CPUError_Type = 13
	// MCA_ERROR_MEM_1_2 enum
	CPUError_Type_MCA_ERROR_MEM_1_2 CPUError_Type = 14
	// MCA_WARNING_MEM_1_2_5 enum
	CPUError_Type_MCA_WARNING_MEM_1_2_5 CPUError_Type = 15
	// MCA_ERROR_MEM_1_2_5 enum
	CPUError_Type_MCA_ERROR_MEM_1_2_5 CPUError_Type = 16
	// MCA_WARNING_MEM_1_2_5_4 enum
	CPUError_Type_MCA_WARNING_MEM_1_2_5_4 CPUError_Type = 17
	// MCA_ERROR_MEM_1_2_5_4 enum
	CPUError_Type_MCA_ERROR_MEM_1_2_5_4 CPUError_Type = 18
	// MCA_WARNING_SYSTEM_EVENT enum
	CPUError_Type_MCA_WARNING_SYSTEM_EVENT CPUError_Type = 19
	// MCA_ERROR_SYSTEM_EVENT enum
	CPUError_Type_MCA_ERROR_SYSTEM_EVENT CPUError_Type = 20
	// MCA_WARNING_PCI_BUS_PARITY enum
	CPUError_Type_MCA_WARNING_PCI_BUS_PARITY CPUError_Type = 21
	// MCA_ERROR_PCI_BUS_PARITY enum
	CPUError_Type_MCA_ERROR_PCI_BUS_PARITY CPUError_Type = 22
	// MCA_WARNING_PCI_BUS_PARITY_NO_INFO enum
	CPUError_Type_MCA_WARNING_PCI_BUS_PARITY_NO_INFO CPUError_Type = 23
	// MCA_ERROR_PCI_BUS_PARITY_NO_INFO enum
	CPUError_Type_MCA_ERROR_PCI_BUS_PARITY_NO_INFO CPUError_Type = 24
	// MCA_WARNING_PCI_BUS_SERR enum
	CPUError_Type_MCA_WARNING_PCI_BUS_SERR CPUError_Type = 25
	// MCA_ERROR_PCI_BUS_SERR enum
	CPUError_Type_MCA_ERROR_PCI_BUS_SERR CPUError_Type = 26
	// MCA_WARNING_PCI_BUS_SERR_NO_INFO enum
	CPUError_Type_MCA_WARNING_PCI_BUS_SERR_NO_INFO CPUError_Type = 27
	// MCA_ERROR_PCI_BUS_SERR_NO_INFO enum
	CPUError_Type_MCA_ERROR_PCI_BUS_SERR_NO_INFO CPUError_Type = 28
	// MCA_WARNING_PCI_BUS_MASTER_ABORT enum
	CPUError_Type_MCA_WARNING_PCI_BUS_MASTER_ABORT CPUError_Type = 29
	// MCA_ERROR_PCI_BUS_MASTER_ABORT enum
	CPUError_Type_MCA_ERROR_PCI_BUS_MASTER_ABORT CPUError_Type = 30
	// MCA_WARNING_PCI_BUS_MASTER_ABORT_NO_INFO enum
	CPUError_Type_MCA_WARNING_PCI_BUS_MASTER_ABORT_NO_INFO CPUError_Type = 31
	// MCA_ERROR_PCI_BUS_MASTER_ABORT_NO_INFO enum
	CPUError_Type_MCA_ERROR_PCI_BUS_MASTER_ABORT_NO_INFO CPUError_Type = 32
	// MCA_WARNING_PCI_BUS_TIMEOUT enum
	CPUError_Type_MCA_WARNING_PCI_BUS_TIMEOUT CPUError_Type = 33
	// MCA_ERROR_PCI_BUS_TIMEOUT enum
	CPUError_Type_MCA_ERROR_PCI_BUS_TIMEOUT CPUError_Type = 34
	// MCA_WARNING_PCI_BUS_TIMEOUT_NO_INFO enum
	CPUError_Type_MCA_WARNING_PCI_BUS_TIMEOUT_NO_INFO CPUError_Type = 35
	// MCA_ERROR_PCI_BUS_TIMEOUT_NO_INFO enum
	CPUError_Type_MCA_ERROR_PCI_BUS_TIMEOUT_NO_INFO CPUError_Type = 36
	// MCA_WARNING_PCI_BUS_UNKNOWN enum
	CPUError_Type_MCA_WARNING_PCI_BUS_UNKNOWN CPUError_Type = 37
	// MCA_ERROR_PCI_BUS_UNKNOWN enum
	CPUError_Type_MCA_ERROR_PCI_BUS_UNKNOWN CPUError_Type = 38
	// MCA_WARNING_PCI_DEVICE enum
	CPUError_Type_MCA_WARNING_PCI_DEVICE CPUError_Type = 39
	// MCA_ERROR_PCI_DEVICE enum
	CPUError_Type_MCA_ERROR_PCI_DEVICE CPUError_Type = 40
	// MCA_WARNING_SMBIOS enum
	CPUError_Type_MCA_WARNING_SMBIOS CPUError_Type = 41
	// MCA_ERROR_SMBIOS enum
	CPUError_Type_MCA_ERROR_SMBIOS CPUError_Type = 42
	// MCA_WARNING_PLATFORM_SPECIFIC enum
	CPUError_Type_MCA_WARNING_PLATFORM_SPECIFIC CPUError_Type = 43
	// MCA_ERROR_PLATFORM_SPECIFIC enum
	CPUError_Type_MCA_ERROR_PLATFORM_SPECIFIC CPUError_Type = 44
	// MCA_WARNING_UNKNOWN enum
	CPUError_Type_MCA_WARNING_UNKNOWN CPUError_Type = 45
	// MCA_ERROR_UNKNOWN enum
	CPUError_Type_MCA_ERROR_UNKNOWN CPUError_Type = 46
	// MCA_WARNING_UNKNOWN_NO_CPU enum
	CPUError_Type_MCA_WARNING_UNKNOWN_NO_CPU CPUError_Type = 47
	// MCA_ERROR_UNKNOWN_NO_CPU enum
	CPUError_Type_MCA_ERROR_UNKNOWN_NO_CPU CPUError_Type = 48
	// MCA_WARNING_CMC_THRESHOLD_EXCEEDED enum
	CPUError_Type_MCA_WARNING_CMC_THRESHOLD_EXCEEDED CPUError_Type = 49
	// MCA_WARNING_CPE_THRESHOLD_EXCEEDED enum
	CPUError_Type_MCA_WARNING_CPE_THRESHOLD_EXCEEDED CPUError_Type = 50
	// MCA_WARNING_CPU_THERMAL_THROTTLED enum
	CPUError_Type_MCA_WARNING_CPU_THERMAL_THROTTLED CPUError_Type = 51
	// MCA_INFO_CPU_THERMAL_THROTTLING_REMOVED enum
	CPUError_Type_MCA_INFO_CPU_THERMAL_THROTTLING_REMOVED CPUError_Type = 52
	// MCA_WARNING_CPU enum
	CPUError_Type_MCA_WARNING_CPU CPUError_Type = 53
	// MCA_ERROR_CPU enum
	CPUError_Type_MCA_ERROR_CPU CPUError_Type = 54
	// MCA_MEMORYHIERARCHY_ERROR enum
	CPUError_Type_MCA_MEMORYHIERARCHY_ERROR CPUError_Type = 55
	// MCA_TLB_ERROR enum
	CPUError_Type_MCA_TLB_ERROR CPUError_Type = 56
	// MCA_BUS_ERROR enum
	CPUError_Type_MCA_BUS_ERROR CPUError_Type = 57
	// MCA_BUS_TIMEOUT_ERROR enum
	CPUError_Type_MCA_BUS_TIMEOUT_ERROR CPUError_Type = 58
	// MCA_INTERNALTIMER_ERROR enum
	CPUError_Type_MCA_INTERNALTIMER_ERROR CPUError_Type = 59
	// MCA_MICROCODE_ROM_PARITY_ERROR enum
	CPUError_Type_MCA_MICROCODE_ROM_PARITY_ERROR CPUError_Type = 60
	// MCA_EXTERNAL_ERROR enum
	CPUError_Type_MCA_EXTERNAL_ERROR CPUError_Type = 61
	// MCA_FRC_ERROR enum
	CPUError_Type_MCA_FRC_ERROR CPUError_Type = 62
)
