// Copyright 2019 (c) Microsoft Corporation.
// Licensed under the MIT license.

//
// Author:
//      Auto Generated on 6/12/2024 using wmigen
//      Source PCIBusError_Type
//////////////////////////////////////////////
package wmi

// PCIBusError_Type
type PCIBusError_Type int

const (
	// MCA_WARNING_CACHE enum
	PCIBusError_Type_MCA_WARNING_CACHE PCIBusError_Type = 1
	// MCA_ERROR_CACHE enum
	PCIBusError_Type_MCA_ERROR_CACHE PCIBusError_Type = 2
	// MCA_WARNING_TLB enum
	PCIBusError_Type_MCA_WARNING_TLB PCIBusError_Type = 3
	// MCA_ERROR_TLB enum
	PCIBusError_Type_MCA_ERROR_TLB PCIBusError_Type = 4
	// MCA_WARNING_CPU_BUS enum
	PCIBusError_Type_MCA_WARNING_CPU_BUS PCIBusError_Type = 5
	// MCA_ERROR_CPU_BUS enum
	PCIBusError_Type_MCA_ERROR_CPU_BUS PCIBusError_Type = 6
	// MCA_WARNING_REGISTER_FILE enum
	PCIBusError_Type_MCA_WARNING_REGISTER_FILE PCIBusError_Type = 7
	// MCA_ERROR_REGISTER_FILE enum
	PCIBusError_Type_MCA_ERROR_REGISTER_FILE PCIBusError_Type = 8
	// MCA_WARNING_MAS enum
	PCIBusError_Type_MCA_WARNING_MAS PCIBusError_Type = 9
	// MCA_ERROR_MAS enum
	PCIBusError_Type_MCA_ERROR_MAS PCIBusError_Type = 10
	// MCA_WARNING_MEM_UNKNOWN enum
	PCIBusError_Type_MCA_WARNING_MEM_UNKNOWN PCIBusError_Type = 11
	// MCA_ERROR_MEM_UNKNOWN enum
	PCIBusError_Type_MCA_ERROR_MEM_UNKNOWN PCIBusError_Type = 12
	// MCA_WARNING_MEM_1_2 enum
	PCIBusError_Type_MCA_WARNING_MEM_1_2 PCIBusError_Type = 13
	// MCA_ERROR_MEM_1_2 enum
	PCIBusError_Type_MCA_ERROR_MEM_1_2 PCIBusError_Type = 14
	// MCA_WARNING_MEM_1_2_5 enum
	PCIBusError_Type_MCA_WARNING_MEM_1_2_5 PCIBusError_Type = 15
	// MCA_ERROR_MEM_1_2_5 enum
	PCIBusError_Type_MCA_ERROR_MEM_1_2_5 PCIBusError_Type = 16
	// MCA_WARNING_MEM_1_2_5_4 enum
	PCIBusError_Type_MCA_WARNING_MEM_1_2_5_4 PCIBusError_Type = 17
	// MCA_ERROR_MEM_1_2_5_4 enum
	PCIBusError_Type_MCA_ERROR_MEM_1_2_5_4 PCIBusError_Type = 18
	// MCA_WARNING_SYSTEM_EVENT enum
	PCIBusError_Type_MCA_WARNING_SYSTEM_EVENT PCIBusError_Type = 19
	// MCA_ERROR_SYSTEM_EVENT enum
	PCIBusError_Type_MCA_ERROR_SYSTEM_EVENT PCIBusError_Type = 20
	// MCA_WARNING_PCI_BUS_PARITY enum
	PCIBusError_Type_MCA_WARNING_PCI_BUS_PARITY PCIBusError_Type = 21
	// MCA_ERROR_PCI_BUS_PARITY enum
	PCIBusError_Type_MCA_ERROR_PCI_BUS_PARITY PCIBusError_Type = 22
	// MCA_WARNING_PCI_BUS_PARITY_NO_INFO enum
	PCIBusError_Type_MCA_WARNING_PCI_BUS_PARITY_NO_INFO PCIBusError_Type = 23
	// MCA_ERROR_PCI_BUS_PARITY_NO_INFO enum
	PCIBusError_Type_MCA_ERROR_PCI_BUS_PARITY_NO_INFO PCIBusError_Type = 24
	// MCA_WARNING_PCI_BUS_SERR enum
	PCIBusError_Type_MCA_WARNING_PCI_BUS_SERR PCIBusError_Type = 25
	// MCA_ERROR_PCI_BUS_SERR enum
	PCIBusError_Type_MCA_ERROR_PCI_BUS_SERR PCIBusError_Type = 26
	// MCA_WARNING_PCI_BUS_SERR_NO_INFO enum
	PCIBusError_Type_MCA_WARNING_PCI_BUS_SERR_NO_INFO PCIBusError_Type = 27
	// MCA_ERROR_PCI_BUS_SERR_NO_INFO enum
	PCIBusError_Type_MCA_ERROR_PCI_BUS_SERR_NO_INFO PCIBusError_Type = 28
	// MCA_WARNING_PCI_BUS_MASTER_ABORT enum
	PCIBusError_Type_MCA_WARNING_PCI_BUS_MASTER_ABORT PCIBusError_Type = 29
	// MCA_ERROR_PCI_BUS_MASTER_ABORT enum
	PCIBusError_Type_MCA_ERROR_PCI_BUS_MASTER_ABORT PCIBusError_Type = 30
	// MCA_WARNING_PCI_BUS_MASTER_ABORT_NO_INFO enum
	PCIBusError_Type_MCA_WARNING_PCI_BUS_MASTER_ABORT_NO_INFO PCIBusError_Type = 31
	// MCA_ERROR_PCI_BUS_MASTER_ABORT_NO_INFO enum
	PCIBusError_Type_MCA_ERROR_PCI_BUS_MASTER_ABORT_NO_INFO PCIBusError_Type = 32
	// MCA_WARNING_PCI_BUS_TIMEOUT enum
	PCIBusError_Type_MCA_WARNING_PCI_BUS_TIMEOUT PCIBusError_Type = 33
	// MCA_ERROR_PCI_BUS_TIMEOUT enum
	PCIBusError_Type_MCA_ERROR_PCI_BUS_TIMEOUT PCIBusError_Type = 34
	// MCA_WARNING_PCI_BUS_TIMEOUT_NO_INFO enum
	PCIBusError_Type_MCA_WARNING_PCI_BUS_TIMEOUT_NO_INFO PCIBusError_Type = 35
	// MCA_ERROR_PCI_BUS_TIMEOUT_NO_INFO enum
	PCIBusError_Type_MCA_ERROR_PCI_BUS_TIMEOUT_NO_INFO PCIBusError_Type = 36
	// MCA_WARNING_PCI_BUS_UNKNOWN enum
	PCIBusError_Type_MCA_WARNING_PCI_BUS_UNKNOWN PCIBusError_Type = 37
	// MCA_ERROR_PCI_BUS_UNKNOWN enum
	PCIBusError_Type_MCA_ERROR_PCI_BUS_UNKNOWN PCIBusError_Type = 38
	// MCA_WARNING_PCI_DEVICE enum
	PCIBusError_Type_MCA_WARNING_PCI_DEVICE PCIBusError_Type = 39
	// MCA_ERROR_PCI_DEVICE enum
	PCIBusError_Type_MCA_ERROR_PCI_DEVICE PCIBusError_Type = 40
	// MCA_WARNING_SMBIOS enum
	PCIBusError_Type_MCA_WARNING_SMBIOS PCIBusError_Type = 41
	// MCA_ERROR_SMBIOS enum
	PCIBusError_Type_MCA_ERROR_SMBIOS PCIBusError_Type = 42
	// MCA_WARNING_PLATFORM_SPECIFIC enum
	PCIBusError_Type_MCA_WARNING_PLATFORM_SPECIFIC PCIBusError_Type = 43
	// MCA_ERROR_PLATFORM_SPECIFIC enum
	PCIBusError_Type_MCA_ERROR_PLATFORM_SPECIFIC PCIBusError_Type = 44
	// MCA_WARNING_UNKNOWN enum
	PCIBusError_Type_MCA_WARNING_UNKNOWN PCIBusError_Type = 45
	// MCA_ERROR_UNKNOWN enum
	PCIBusError_Type_MCA_ERROR_UNKNOWN PCIBusError_Type = 46
	// MCA_WARNING_UNKNOWN_NO_CPU enum
	PCIBusError_Type_MCA_WARNING_UNKNOWN_NO_CPU PCIBusError_Type = 47
	// MCA_ERROR_UNKNOWN_NO_CPU enum
	PCIBusError_Type_MCA_ERROR_UNKNOWN_NO_CPU PCIBusError_Type = 48
	// MCA_WARNING_CMC_THRESHOLD_EXCEEDED enum
	PCIBusError_Type_MCA_WARNING_CMC_THRESHOLD_EXCEEDED PCIBusError_Type = 49
	// MCA_WARNING_CPE_THRESHOLD_EXCEEDED enum
	PCIBusError_Type_MCA_WARNING_CPE_THRESHOLD_EXCEEDED PCIBusError_Type = 50
	// MCA_WARNING_CPU_THERMAL_THROTTLED enum
	PCIBusError_Type_MCA_WARNING_CPU_THERMAL_THROTTLED PCIBusError_Type = 51
	// MCA_INFO_CPU_THERMAL_THROTTLING_REMOVED enum
	PCIBusError_Type_MCA_INFO_CPU_THERMAL_THROTTLING_REMOVED PCIBusError_Type = 52
	// MCA_WARNING_CPU enum
	PCIBusError_Type_MCA_WARNING_CPU PCIBusError_Type = 53
	// MCA_ERROR_CPU enum
	PCIBusError_Type_MCA_ERROR_CPU PCIBusError_Type = 54
	// MCA_MEMORYHIERARCHY_ERROR enum
	PCIBusError_Type_MCA_MEMORYHIERARCHY_ERROR PCIBusError_Type = 55
	// MCA_TLB_ERROR enum
	PCIBusError_Type_MCA_TLB_ERROR PCIBusError_Type = 56
	// MCA_BUS_ERROR enum
	PCIBusError_Type_MCA_BUS_ERROR PCIBusError_Type = 57
	// MCA_BUS_TIMEOUT_ERROR enum
	PCIBusError_Type_MCA_BUS_TIMEOUT_ERROR PCIBusError_Type = 58
	// MCA_INTERNALTIMER_ERROR enum
	PCIBusError_Type_MCA_INTERNALTIMER_ERROR PCIBusError_Type = 59
	// MCA_MICROCODE_ROM_PARITY_ERROR enum
	PCIBusError_Type_MCA_MICROCODE_ROM_PARITY_ERROR PCIBusError_Type = 60
	// MCA_EXTERNAL_ERROR enum
	PCIBusError_Type_MCA_EXTERNAL_ERROR PCIBusError_Type = 61
	// MCA_FRC_ERROR enum
	PCIBusError_Type_MCA_FRC_ERROR PCIBusError_Type = 62
)
