// Copyright 2019 (c) Microsoft Corporation.
// Licensed under the MIT license.

//
// Author:
//      Auto Generated on 6/12/2024 using wmigen
//      Source RSPNDR_Flags
//////////////////////////////////////////////
package wmi

// RSPNDR_Flags
type RSPNDR_Flags int

const (
	// TRACE_CLASS_CALL enum
	RSPNDR_Flags_TRACE_CLASS_CALL RSPNDR_Flags = 1
	// TRACE_CLASS_DISPATCH enum
	RSPNDR_Flags_TRACE_CLASS_DISPATCH RSPNDR_Flags = 2
	// TRACE_CLASS_REQUEST enum
	RSPNDR_Flags_TRACE_CLASS_REQUEST RSPNDR_Flags = 3
	// TRACE_CLASS_BINDING enum
	RSPNDR_Flags_TRACE_CLASS_BINDING RSPNDR_Flags = 4
	// TRACE_CLASS_SESSION enum
	RSPNDR_Flags_TRACE_CLASS_SESSION RSPNDR_Flags = 5
	// TRACE_CLASS_QUIESCENT enum
	RSPNDR_Flags_TRACE_CLASS_QUIESCENT RSPNDR_Flags = 6
	// TRACE_CLASS_HELLO enum
	RSPNDR_Flags_TRACE_CLASS_HELLO RSPNDR_Flags = 7
	// TRACE_CLASS_COMMAND enum
	RSPNDR_Flags_TRACE_CLASS_COMMAND RSPNDR_Flags = 8
	// TRACE_CLASS_EMIT enum
	RSPNDR_Flags_TRACE_CLASS_EMIT RSPNDR_Flags = 9
	// TRACE_CLASS_THREAD enum
	RSPNDR_Flags_TRACE_CLASS_THREAD RSPNDR_Flags = 10
	// TRACE_CLASS_TIMER enum
	RSPNDR_Flags_TRACE_CLASS_TIMER RSPNDR_Flags = 11
	// TRACE_CLASS_QOS enum
	RSPNDR_Flags_TRACE_CLASS_QOS RSPNDR_Flags = 12
	// TRACE_CLASS_NLC enum
	RSPNDR_Flags_TRACE_CLASS_NLC RSPNDR_Flags = 13
)
